# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'Musicer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'R.swift'
  pod 'SnapKit', '~> 5.0.1'
#  pod 'NVActivityIndicatorView'
  #pod "GCDWebServer", "~> 3.0"
  pod "GCDWebServer/WebUploader", "~> 3.0"
  pod 'FLEX', :configurations => ['Debug']
  pod 'Kingfisher', '~> 6.1.0'
#  pod 'RealmSwift', '~> 10.5.0'
  pod 'WCDB.swift', '~> 1.0.8.2'

end
